# Generated by Django 5.2.4 on 2025-12-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_image_uploaded_at_alter_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
